<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3"><PrivateAssets>all</PrivateAssets></PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup><Using Include="Xunit" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Shared\Shared.Kernel\Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\src\Services\Report\Report.Domain\Report.Domain.csproj" />
    <ProjectReference Include="..\..\src\Services\Notification\Notification.Domain\Notification.Domain.csproj" />
    <ProjectReference Include="..\..\src\Services\Notification\Notification.Application\Notification.Application.csproj" />
    <ProjectReference Include="..\..\src\Services\Notification\Notification.Infrastructure\Notification.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Services\Notification\Notification.API\Notification.API.csproj" />
    <ProjectReference Include="..\..\src\Services\Report\Report.Infrastructure\Report.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Services\Report\Report.Application\Report.Application.csproj" />
    <ProjectReference Include="..\..\src\Services\Report\Report.API\Report.API.csproj" />
    <ProjectReference Include="..\..\src\Services\Finance\Finance.Domain\Finance.Domain.csproj" />
    <ProjectReference Include="..\..\src\Services\Finance\Finance.Application\Finance.Application.csproj" />
    <ProjectReference Include="..\..\src\Services\Finance\Finance.Infrastructure\Finance.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Services\Finance\Finance.API\Finance.API.csproj" />
    <ProjectReference Include="..\..\src\Services\Auth\Auth.Domain\Auth.Domain.csproj" />
    <ProjectReference Include="..\..\src\Services\Auth\Auth.Infrastructure\Auth.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Services\Auth\Auth.API\Auth.API.csproj" />
    <ProjectReference Include="..\..\src\Services\Club\Club.Application\Club.Application.csproj" />
    <ProjectReference Include="..\..\src\Services\Club\Club.Infrastructure\Club.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Services\Club\Club.API\Club.API.csproj" />
  </ItemGroup>
</Project>
