name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        cache: true
        
    - name: Restore dependencies
      run: dotnet restore FPTU_Club_Report_System.sln
      
    - name: Build
      run: dotnet build FPTU_Club_Report_System.sln --no-restore --configuration Release
      
    - name: Test
      run: dotnet test FPTU_Club_Report_System.sln --no-build --verbosity normal --configuration Release
